<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="16166" started-at="2025-03-19T20:59:05Z" finished-at="2025-03-19T20:59:21Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="16166" started-at="2025-03-19T20:59:05Z" finished-at="2025-03-19T20:59:21Z">
      <class name="com.org.AccessibilityPlayWright.NewPlaywrightAllyTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.org.AccessibilityPlayWright.NewPlaywrightAllyTest@76908cc0]" name="setUp" is-config="true" duration-ms="9588" started-at="2025-03-19T16:59:05Z" finished-at="2025-03-19T16:59:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="accessibilityTesting()[pri:0, instance:com.org.AccessibilityPlayWright.NewPlaywrightAllyTest@76908cc0]" name="accessibilityTesting" duration-ms="6235" started-at="2025-03-19T16:59:14Z" finished-at="2025-03-19T16:59:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.org.AccessibilityPlayWright.NewPlaywrightAllyTest.accessibilityTesting(NewPlaywrightAllyTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- accessibilityTesting -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.org.AccessibilityPlayWright.NewPlaywrightAllyTest@76908cc0]" name="tearDown" is-config="true" duration-ms="300" started-at="2025-03-19T16:59:20Z" finished-at="2025-03-19T16:59:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.org.AccessibilityPlayWright.NewPlaywrightAllyTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
